'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type FaIconChooserCustomEvent, type IconChooserResult } from "@fortawesome/fa-icon-chooser";
import { FaIconChooser as FaIconChooserElement, defineCustomElement as defineFaIconChooser } from "@fortawesome/fa-icon-chooser/dist/components/fa-icon-chooser.js";
import { FaIcon as FaIconElement, defineCustomElement as defineFaIcon } from "@fortawesome/fa-icon-chooser/dist/components/fa-icon.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type FaIconEvents = NonNullable<unknown>;

export const FaIcon: StencilReactComponent<FaIconElement, FaIconEvents> = /*@__PURE__*/ createComponent<FaIconElement, FaIconEvents>({
    tagName: 'fa-icon',
    elementClass: FaIconElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as FaIconEvents,
    defineCustomElement: defineFaIcon
});

type FaIconChooserEvents = { onFinish: EventName<FaIconChooserCustomEvent<IconChooserResult>> };

export const FaIconChooser: StencilReactComponent<FaIconChooserElement, FaIconChooserEvents> = /*@__PURE__*/ createComponent<FaIconChooserElement, FaIconChooserEvents>({
    tagName: 'fa-icon-chooser',
    elementClass: FaIconChooserElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onFinish: 'finish' } as FaIconChooserEvents,
    defineCustomElement: defineFaIconChooser
});
