/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IconChooserResult, QueryHandler } from "./components/fa-icon-chooser/fa-icon-chooser";
export namespace Components {
    interface FaIconChooser {
        /**
          * Whether pro icons should be enabled.
         */
        "enablePro": boolean;
        "handleQuery": QueryHandler;
        /**
          * A kit token identifying a kit in which to find icons. Takes precedence over the version prop if provided: the version associated with the kit will be used for searching.
         */
        "kitToken"?: string;
        /**
          * Font Awesome version in which to find icons.
         */
        "version"?: string;
    }
}
declare global {
    interface HTMLFaIconChooserElement extends Components.FaIconChooser, HTMLStencilElement {
    }
    var HTMLFaIconChooserElement: {
        prototype: HTMLFaIconChooserElement;
        new (): HTMLFaIconChooserElement;
    };
    interface HTMLElementTagNameMap {
        "fa-icon-chooser": HTMLFaIconChooserElement;
    }
}
declare namespace LocalJSX {
    interface FaIconChooser {
        /**
          * Whether pro icons should be enabled.
         */
        "enablePro"?: boolean;
        "handleQuery"?: QueryHandler;
        /**
          * A kit token identifying a kit in which to find icons. Takes precedence over the version prop if provided: the version associated with the kit will be used for searching.
         */
        "kitToken"?: string;
        "onFinish"?: (event: CustomEvent<IconChooserResult>) => void;
        /**
          * Font Awesome version in which to find icons.
         */
        "version"?: string;
    }
    interface IntrinsicElements {
        "fa-icon-chooser": FaIconChooser;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fa-icon-chooser": LocalJSX.FaIconChooser & JSXBase.HTMLAttributes<HTMLFaIconChooserElement>;
        }
    }
}
